version: "3.9"
services:
  wordpress:
    build:
      context: .docker/wordpress
      dockerfile: Dockerfile
    volumes:
      - "./.wp:/var/www/html"
      - "./wp-plugins/harpoon-proxy-cache-purge:/var/www/html/wp-content/plugins/harpoon-proxy-cache-purge"
    environment:
      WORPDRESS_DB_HOST: "${DB_HOST:-mysql}:${DB_PORT:-3306}"
      WORDPRESS_DB_USER: "${DB_USER:-wordpress}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD:-wordpress}"
      WORDPRESS_DB_NAME: "${DB_NAME:-wordpress}"
      WORDPRESS_DEBUG: "${WP_DEBUG:-}"
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', 6379 );
        define( 'WP_REDIS_PREFIX', 'test:' );
        define( 'WP_REDIS_DATABASE', 1 );
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      XDEBUG_SESSION: "${XDEBUG_IDE_KEY:-ANY}"
      XDEBUG_CONFIG: "client_host=${XDEBUG_CLIENT:-host.docker.internal} client_port=${XDEBUG_PORT:-9003}"
    user: "${DOCKER_USER:-1000}:${DOCKER_GROUP:-1000}"
    depends_on:
      redis:
        condition: service_started
      nginx:
        condition: service_started
      mysql:
        condition: service_healthy
  nginx:
    build:
      context: .docker/nginx
      args:
        ENABLED_MODULES: "echo srcache redis2 redis cachepurge ndk njs brotli set-misc"
    volumes:
      - "./dist:/etc/nginx/njs"
      - "./lua:/etc/nginx/lua"
      - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./.docker/nginx/conf.d:/etc/nginx/conf.d"
      - "./.docker/nginx/include.d:/etc/nginx/include.d"
      - "./config.sample.json:/etc/nginx/config.json"
      - "./config.sample.yaml:/etc/nginx/config.yaml"
    ports:
      - "${FORWARD_HOST:-0.0.0.0}:${FORWARD_HTTP_PORT:-80}:80"
    depends_on:
      - redis
  mysql:
    image: mysql:8.0.33
    ports:
      - "${FORWARD_HOST:-0.0.0.0}:${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - "./.docker/mysql/data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "${DB_NAME:-wordpress}"
      MYSQL_USER: "${DB_USER:-wordpress}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-wordpress}"
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 2s
      timeout: 2s
      start_period: 60s
      retries: 3
  redis:
    image: redis:alpine
    ports:
      - "${FORWARD_HOST:-0.0.0.0}:${FORWARD_REDIS_PORT:-6379}:6379"
